import './globals.css'
import type { Metadata } from 'next'
import Navbar from"../components/Nav";
import ProviderWrapper from '@/components/ProviderWrapper';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
         {/* <Nav/> */}
      <body>
        <ProviderWrapper>
          <Navbar/>
          <div className="container mx-auto min-h-screen">{children}</div>
        </ProviderWrapper>
      </body>
    </html>
  )
}
