import './globals.css'
import type { Metadata } from 'next'
import Navbar from"../components/Nav";
import ProviderWrapper from '@/context/ProviderWrapper';
import { Inter } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: 'Tutor Sheet',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
         {/* <Nav/> */}
      <body >
        <ProviderWrapper>
          <Navbar/>
          <div className="container mx-auto min-h-screen">{children}</div>
        </ProviderWrapper>
      </body>
    </html>
  )
}
